pipeline{
    agent any 
    environment {
        NAME = "Axel"
    }
    stages{
        stage("Coucou"){
            steps{
                echo "Coucou ${env.NAME}"
            }
        }
    }
}